### PR TITLE
Issue #KN-50: Angular migration from version 10 to 11

### PR DESCRIPTION
**Pull request by gouravmore**
Issue #KN-50: Angular migration from version 10 to 11
Implementation video link:- https://drive.google.com/file/d/1TmJmHyCKWkF8A7L6VnYwhFJazxbHXetX/view?usp=sharing

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by HarishGangula — APPROVED** [review]
Share the player video after migration to 11 with all the scenarios to merge this PR

**Comment by gouravmore** [comment]
@HarishGangula Updated the PR description with video link

**Comment by HarishGangula** [comment]
@gouravmore  Don't have access to see

**Comment by HarishGangula** [comment]
@gouravmore  Update the ticket with change in file sizes and overall player size and load time change before and after migration

**Pull request merged**
